/**
 * ACP SDK golden vector tests.
 *
 * Each vector was generated by desktop/sdk/scripts/export_vectors.py using the
 * same Python serialize_event() calls as tests/protocol/test_event_golden.py.
 * Vectors are committed to the repo; this test requires no Python at runtime.
 *
 * For each vector:
 *   1. Parse the serialized JSON string as an Envelope → verify kind matches.
 *   2. parseEvent() the data payload → verify kind field on result.
 *   3. For each expected_data field → verify the parsed event has it with the
 *      correct value.
 *   4. Special invariant: verify_verdict events with status "unverifiable"
 *      must not be mapped to passed/green.
 *   5. proactive_suggestion.requires_confirmation must always be true.
 */

import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { describe, it } from "node:test";
import assert from "node:assert/strict";

import { parseEnvelope, parseEvent } from "../src/parse.js";
import type { ParsedEvent } from "../src/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const vectorsPath = join(__dirname, "vectors.json");

interface Vector {
  kind: string;
  serialized: string;
  expected_data: Record<string, unknown>;
}

const vectors: Vector[] = JSON.parse(readFileSync(vectorsPath, "utf-8")) as Vector[];

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Parse a Python serialize_event() output string.
 * Format: {"kind": "...", "data": {...}}
 * This is NOT a full ACP envelope (no v/seq/id/ts); it's the inner event JSON
 * written to the JSONL store and used by the golden test suite.
 */
function parseVector(v: Vector): { ev: ParsedEvent; data: Record<string, unknown> } {
  const obj = JSON.parse(v.serialized) as Record<string, unknown>;
  assert.equal(obj["kind"], v.kind, `serialized kind mismatch for ${v.kind}`);
  const data = obj["data"] as Record<string, unknown>;
  const ev = parseEvent(v.kind, data);
  return { ev, data };
}

// ── Vector tests ─────────────────────────────────────────────────────────────

describe("ACP golden vectors", () => {
  for (const v of vectors) {
    it(`parse and field-check: ${v.kind}`, () => {
      const { ev } = parseVector(v);

      // kind discriminant must be preserved (or "unknown" for genuinely unknown kinds)
      assert.equal(ev.kind, v.kind, `kind field mismatch`);

      // Every expected_data field must appear on the parsed event with correct value
      for (const [key, expected] of Object.entries(v.expected_data)) {
        const actual = (ev as Record<string, unknown>)[key];
        assert.deepEqual(
          actual, expected,
          `field "${key}" mismatch for kind=${v.kind}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`,
        );
      }
    });
  }

  // ── Invariant: unverifiable MUST NOT be mapped to passed ────────────────
  it("verify_verdict unverifiable is never mapped to passed/green (synthetic envelope)", () => {
    // Synthetic full ACP envelope — verifies the parseEnvelope + parseEvent path.
    const syntheticVerdictUnverifiable = JSON.stringify({
      v: 1, seq: 1, kind: "verify_verdict", id: "x", ts: 0.0, session: "s", run: "r",
      data: {
        verdict: {
          status: "unverifiable",
          detail: "no cmd",
          verify_cmd: null,
          attempts: 0,
          tampered: [],
          self_verified: false,
        },
      },
    });
    const envelope = parseEnvelope(syntheticVerdictUnverifiable);
    assert.ok(envelope !== null);
    const ev = parseEvent(envelope.kind, envelope.data) as Record<string, unknown>;
    const verdict = (ev["verdict"] as Record<string, unknown>);
    assert.equal(
      verdict["status"],
      "unverifiable",
      "unverifiable status must be preserved as-is, not mapped to passed",
    );
  });

  // ── Invariant: verify_verdict Python-exported vectors pin all three states ─
  it("verify_verdict Python vectors cover all three Verdict states (passed/failed/unverifiable)", () => {
    const verdictVectors = vectors.filter((v) => v.kind === "verify_verdict");
    assert.ok(verdictVectors.length >= 3, "expected at least 3 verify_verdict vectors (one per state)");
    const statuses = verdictVectors.map((v) => {
      const { ev } = parseVector(v);
      const verdict = (ev as Record<string, unknown>)["verdict"] as Record<string, unknown>;
      return verdict["status"] as string;
    });
    assert.ok(statuses.includes("passed"), "expected a passed verify_verdict vector");
    assert.ok(statuses.includes("failed"), "expected a failed verify_verdict vector");
    assert.ok(statuses.includes("unverifiable"), "expected an unverifiable verify_verdict vector");
    // Core invariant: unverifiable must never be coerced to passed in any of the vectors.
    for (const v of verdictVectors) {
      const { ev } = parseVector(v);
      const verdict = (ev as Record<string, unknown>)["verdict"] as Record<string, unknown>;
      if (verdict["status"] === "unverifiable") {
        assert.notEqual(
          verdict["status"], "passed",
          "Python-exported unverifiable verdict must not be mapped to passed",
        );
      }
    }
  });

  // ── Invariant: proactive_suggestion.requires_confirmation is always true ──
  it("proactive_suggestion.requires_confirmation is always true", () => {
    const found = vectors.filter((v) => v.kind === "proactive_suggestion");
    assert.ok(found.length > 0, "expected at least one proactive_suggestion vector");
    for (const v of found) {
      const { ev } = parseVector(v);
      assert.equal(
        (ev as Record<string, unknown>)["requires_confirmation"],
        true,
        "requires_confirmation must always be true (protocol invariant)",
      );
    }
  });

  // ── Invariant: tool_receipt vector exists and pins Receipt wire shape ────
  it("tool_receipt Python vector exists and receipt fields are present", () => {
    const found = vectors.filter((v) => v.kind === "tool_receipt");
    assert.ok(found.length > 0, "expected at least one tool_receipt vector");
    const { ev } = parseVector(found[0]);
    const receipt = (ev as Record<string, unknown>)["receipt"] as Record<string, unknown>;
    assert.ok(receipt !== undefined && receipt !== null, "tool_receipt must have a receipt field");
    assert.ok(typeof receipt["action"] === "string", "receipt.action must be a string");
    assert.ok(typeof receipt["sig"] === "string", "receipt.sig must be a string");
  });

  // ── Invariant: computer_action vector exists (guards against silent loss ──
  //    when vectors.json is regenerated by export_vectors.py) ────────────────
  it("computer_action Python vector exists and core fields are present", () => {
    const found = vectors.filter((v) => v.kind === "computer_action");
    assert.ok(found.length > 0, "expected at least one computer_action vector");
    const { ev } = parseVector(found[0]);
    const e = ev as Record<string, unknown>;
    assert.ok(typeof e["kind_action"] === "string", "computer_action.kind_action must be a string");
    assert.ok(typeof e["ok"] === "boolean", "computer_action.ok must be a boolean");
    assert.ok(typeof e["detail"] === "string", "computer_action.detail must be a string");
  });

  // ── Forward compatibility: unknown kind produces { kind:"unknown", raw } ──
  it("unknown kind produces forward-compatible { kind:'unknown', raw }", () => {
    const unknownData = { some_future_field: 42 };
    const ev = parseEvent("future_kind_v99", unknownData);
    assert.equal(ev.kind, "unknown");
    assert.deepEqual((ev as Record<string, unknown>)["raw"], unknownData);
  });

  // ── parseEnvelope: missing required fields returns null ─────────────────
  it("parseEnvelope returns null for structurally invalid JSON", () => {
    assert.equal(parseEnvelope("not json{{{"), null);
    assert.equal(parseEnvelope("null"), null);
    assert.equal(parseEnvelope("[1,2,3]"), null);
    assert.equal(parseEnvelope('{"kind":"x"}'), null, "missing seq");
    assert.equal(parseEnvelope('{"kind":"x","seq":1}'), null, "missing v");
    assert.equal(parseEnvelope('{"v":1,"seq":1}'), null, "missing kind");
  });
});
