"""CORE2 cluster catalog — verify_gate / snapshot / harness / models / loop residuals /
contracts / runtime / config_base / external_surfaces / app_factory / protocol/events /
ledger / sandbox_child / fakeloop / tui widgets / input (stt / recorder / attachments).

ZH values = verbatim original Chinese strings (so ARGOS_LANG=zh legacy assertions pass).
EN values = natural, precise English equivalents.
"""
from __future__ import annotations

EN: dict[str, str] = {
    # ── verify_gate ──────────────────────────────────────────────────────────
    "core2.verify_gate.tampered": (
        "Protected files have been modified: {files} — verification result cannot be trusted."
    ),
    "core2.verify_gate.no_cmd": "(no verify_cmd; machine-check verification not performed)",
    "core2.verify_gate.trivial": (
        "Verification command `{cmd}` is trivial (always passes, verifies nothing) — "
        "rejected as machine-check verification; falling back to 'unverifiable' honest path (never faking green)."
    ),
    "core2.verify_gate.self_verified_weak": (
        "[self_verified] Weaker signal: test auto-generated by system under reviewer role + canary guard "
        "(empty workspace must be non-zero verified); no user-level verify present. {detail}"
    ),
    "core2.verify_gate.self_verified_failed": (
        "[self_verified failed] Auto-generated test did not pass in real workspace: {detail}"
    ),
    "core2.verify_gate.parse_failed": "Verification command parse failed: {error}",
    "core2.verify_gate.not_allowlisted": "Verification command not in allowlist: {cmd}",
    "core2.verify_gate.timeout": (
        "[timeout] Verification command `{cmd}` exceeded {timeout}s — "
        "downgraded to 'unverifiable' (will not fake passing)."
    ),
    "core2.verify_gate.exec_failed": "Verification execution failed: {error}",

    # ── snapshot ─────────────────────────────────────────────────────────────
    "core2.snapshot.tar_not_found_restore": "Snapshot file not found: {path}",
    "core2.snapshot.mkdir_failed": "Failed to create parent directory: {error}",
    "core2.snapshot.tar_read_failed": "Tar read failed: {error}",
    "core2.snapshot.path_cage_rejected": "Path cage rejected (../ escape or invalid path): {error}",
    "core2.snapshot.tar_not_found_file": "Snapshot file not found: {path}",
    "core2.snapshot.new_file_delete_failed": "Failed to delete newly-created file: {error}",
    "core2.snapshot.mkdir_failed_file": "Failed to create parent directory: {error}",
    "core2.snapshot.extractfile_none": "tar extractfile returned None",
    "core2.snapshot.tar_read_failed_file": "Tar read failed: {error}",

    # ── harness ───────────────────────────────────────────────────────────────
    "core2.harness.must_start_plan": "First enter_phase must start from plan; received {phase}.",
    "core2.harness.no_retreat": (
        "Phase cannot go backward: current {current} → attempted to return to {phase}."
    ),
    "core2.harness.no_skip": (
        "Phase cannot be skipped: current {current} → attempted to jump directly to {phase}"
        " (must pass through {order})."
    ),

    # ── models ────────────────────────────────────────────────────────────────
    "core2.models.pool_empty": "CredentialPool requires at least 1 key",
    "core2.models.all_terminal": "All credentials have been terminally removed; no key available",

    # ── runtime ───────────────────────────────────────────────────────────────
    "core2.runtime.deleted": "(deleted)",
    "core2.runtime.modified": "(modified)",
    "core2.runtime.added": "(added)",

    # ── config_base ──────────────────────────────────────────────────────────
    "core2.config_base.read_failed": "Error reading {path}: {error}",
    "core2.config_base.invalid_json": "{path} is not valid JSON: {error}",
    "core2.config_base.not_object": "Top-level value must be an object",

    # ── external_surfaces ────────────────────────────────────────────────────
    "core2.external.hooks": (
        "hooks (~/.argos/hooks.json): lifecycle hooks run your configured commands outside the sandbox"
    ),
    "core2.external.lsp": (
        "lsp (~/.argos/lsp.json): language server runs outside the sandbox as a subprocess"
    ),
    "core2.external.mcp": (
        "mcp (~/.argos/mcp.json): MCP server runs outside the sandbox as a subprocess"
    ),

    # ── app_factory ──────────────────────────────────────────────────────────
    "core2.app_factory.no_api_key": (
        "No API key configured for the current model. "
        "Run `argos setup` to connect a model, or set the corresponding environment variable. "
        "Argos will not pretend to run."
    ),

    # ── protocol/events ──────────────────────────────────────────────────────
    "core2.events.proactive_action_invalid": (
        "ProactiveSuggestionEvent.action must be 'run' or 'dream'; received {action!r}"
    ),

    # ── ledger/store ─────────────────────────────────────────────────────────
    "core2.ledger.undo_done": "Undo complete: file changes from the start of the run have been restored.",

    # ── sandbox/_sandbox_child ────────────────────────────────────────────────
    "core2.sandbox_child.broker_closed": "Error: broker channel closed; denying by default.",

    # ── loop (residuals) ─────────────────────────────────────────────────────
    "core2.loop.m8_assert": (
        "M8 safety invariant: namespace spawned by loop must never carry __authorized_imports__ "
        "(smolagents treats '*' as allow-all; model control would bypass the AST restriction layer)."
    ),
    "core2.loop.skill_header": "## Skills: {name}\n{description}\n\n{body}",

    # ── fakeloop ─────────────────────────────────────────────────────────────
    "core2.fakeloop.plan_prefix": "Plan: {goal}\n",
    "core2.fakeloop.done": "Complete, all verification checks passed.\n",
    "core2.fakeloop.escalation_reason": "3 consecutive verify rounds failed; cannot converge on its own",
    "core2.fakeloop.error_message": "Giving up; reporting honestly",

    # ── tui/widgets/transcript ────────────────────────────────────────────────
    "core2.transcript.thinking": "Thinking…",

    # ── tui/widgets/thinking ─────────────────────────────────────────────────
    "core2.thinking.label": "Thinking…",

    # ── input/stt ────────────────────────────────────────────────────────────
    "core2.stt.local_unavailable": (
        "Local STT unavailable: faster-whisper is not installed "
        "(should be bundled with the base install)."
    ),
    "core2.stt.local_failed": "Local transcription failed: {error}",
    "core2.stt.cloud_sdk_missing": (
        "Cloud STT requires the openai SDK: pip install 'argos-agent[cloud-stt]'."
    ),
    "core2.stt.cloud_failed": "Cloud transcription failed: {error}",

    # ── input/recorder ────────────────────────────────────────────────────────
    "core2.recorder.backend_unavailable": (
        "Cannot load audio backend (sounddevice/PortAudio). "
        "On Linux: `apt install libportaudio2`; other platforms should bundle the wheel."
    ),
    "core2.recorder.start_failed": "Failed to start recording (no microphone?): {error}",
    "core2.recorder.not_recording": "Not currently recording.",
    "core2.recorder.no_audio": "No audio captured (microphone may have no input).",

    # ── input/attachments ────────────────────────────────────────────────────
    "core2.attachments.unsupported_format": (
        "Unsupported image format: {media_type!r}. Supported formats: {supported}"
    ),
    "core2.attachments.too_large": (
        "Image exceeds 5 MB limit (actual={size:.1f} MB). Please compress or crop and retry."
    ),
}

ZH: dict[str, str] = {
    # ── verify_gate ──────────────────────────────────────────────────────────
    "core2.verify_gate.tampered": (
        "验证依赖的受保护文件被改动:{files} —— 通过不可信。"
    ),
    "core2.verify_gate.no_cmd": "(无 verify_cmd，未做机检验证)",
    "core2.verify_gate.trivial": (
        "验证命令 `{cmd}` 是 trivial(永远通过、什么都不验证)—— "
        "拒绝当作机检验证,落'未验证'诚实路径(绝不假绿)。"
    ),
    "core2.verify_gate.self_verified_weak": (
        "[self_verified] 较弱:测试由系统按 reviewer 角色 + canary 守卫自动生成"
        "(空 workspace 必非 0 验过);用户级 verify 不在场。{detail}"
    ),
    "core2.verify_gate.self_verified_failed": (
        "[self_verified failed] 自造测试在真 workspace 未通过:{detail}"
    ),
    "core2.verify_gate.parse_failed": "验证命令解析失败：{error}",
    "core2.verify_gate.not_allowlisted": "验证命令不在白名单：{cmd}",
    "core2.verify_gate.timeout": (
        "[超时] 验证命令 `{cmd}` 超过 {timeout}s 未完成 —— "
        "降级为'无法验证'(不会假装通过)。"
    ),
    "core2.verify_gate.exec_failed": "验证执行失败：{error}",

    # ── snapshot ─────────────────────────────────────────────────────────────
    "core2.snapshot.tar_not_found_restore": "快照文件不存在:{path}",
    "core2.snapshot.mkdir_failed": "创建父目录失败:{error}",
    "core2.snapshot.tar_read_failed": "tar 读取失败:{error}",
    "core2.snapshot.path_cage_rejected": "路径牢笼拒绝(../ 逃逸或非法路径):{error}",
    "core2.snapshot.tar_not_found_file": "快照文件不存在:{path}",
    "core2.snapshot.new_file_delete_failed": "新建文件删除失败:{error}",
    "core2.snapshot.mkdir_failed_file": "创建父目录失败:{error}",
    "core2.snapshot.extractfile_none": "tar extractfile 返回 None",
    "core2.snapshot.tar_read_failed_file": "tar 读取失败:{error}",

    # ── harness ───────────────────────────────────────────────────────────────
    "core2.harness.must_start_plan": "首次 enter_phase 必须从 plan 开始,收到 {phase}。",
    "core2.harness.no_retreat": (
        "阶段不可倒退:当前 {current} → 试图回到 {phase}。"
    ),
    "core2.harness.no_skip": (
        "阶段不可跳:当前 {current} → 试图直接到 {phase}"
        "(必须依次经过 {order})。"
    ),

    # ── models ────────────────────────────────────────────────────────────────
    "core2.models.pool_empty": "CredentialPool 需要至少 1 个 key",
    "core2.models.all_terminal": "所有 credential 均已 terminal 剔除,无可用 key",

    # ── runtime ───────────────────────────────────────────────────────────────
    "core2.runtime.deleted": "(被删除)",
    "core2.runtime.modified": "(被修改)",
    "core2.runtime.added": "(新增)",

    # ── config_base ──────────────────────────────────────────────────────────
    "core2.config_base.read_failed": "读 {path} 失败: {error}",
    "core2.config_base.invalid_json": "{path} 不是合法 JSON: {error}",
    "core2.config_base.not_object": "顶层必须是 object",

    # ── external_surfaces ────────────────────────────────────────────────────
    "core2.external.hooks": (
        "hooks(~/.argos/hooks.json):生命周期钩子在沙箱外运行你配置的命令"
    ),
    "core2.external.lsp": (
        "lsp(~/.argos/lsp.json):language server 在沙箱外作为子进程运行"
    ),
    "core2.external.mcp": (
        "mcp(~/.argos/mcp.json):MCP server 在沙箱外作为子进程运行"
    ),

    # ── app_factory ──────────────────────────────────────────────────────────
    "core2.app_factory.no_api_key": (
        "未配置当前模型的 API key。请运行 `argos setup` 接入模型,或设置对应环境变量。"
        "Argos 不会假装能跑。"
    ),

    # ── protocol/events ──────────────────────────────────────────────────────
    "core2.events.proactive_action_invalid": (
        "ProactiveSuggestionEvent.action 必须是 'run' 或 'dream'，收到 {action!r}"
    ),

    # ── ledger/store ─────────────────────────────────────────────────────────
    "core2.ledger.undo_done": "撤销完成:已还原 run 起点的文件改动。",

    # ── sandbox/_sandbox_child ────────────────────────────────────────────────
    "core2.sandbox_child.broker_closed": "错误:broker 通道关闭,默认拒绝。",

    # ── loop (residuals) ─────────────────────────────────────────────────────
    "core2.loop.m8_assert": (
        "M8 安全不变量:loop spawn 的 namespace 绝不可携带 __authorized_imports__"
        "(smolagents 把 '*' 当 allow-all,模型可控会绕过 AST 限制层)。"
    ),
    "core2.loop.skill_header": "## 技能:{name}\n{description}\n\n{body}",

    # ── fakeloop ─────────────────────────────────────────────────────────────
    "core2.fakeloop.plan_prefix": "计划:{goal}\n",
    "core2.fakeloop.done": "完成,已验证全绿。\n",
    "core2.fakeloop.escalation_reason": "连续 3 轮 verify 未过,无法自行收敛",
    "core2.fakeloop.error_message": "放弃,诚实上报",

    # ── tui/widgets/transcript ────────────────────────────────────────────────
    "core2.transcript.thinking": "思考中…",

    # ── tui/widgets/thinking ─────────────────────────────────────────────────
    "core2.thinking.label": "思考中…",

    # ── input/stt ────────────────────────────────────────────────────────────
    "core2.stt.local_unavailable": (
        "本地 STT 不可用:未安装 faster-whisper(语音应随基础安装自带)。"
    ),
    "core2.stt.local_failed": "本地转写失败:{error}",
    "core2.stt.cloud_sdk_missing": (
        "云端 STT 需要 openai SDK:pip install 'argos-agent[cloud-stt]'。"
    ),
    "core2.stt.cloud_failed": "云端转写失败:{error}",

    # ── input/recorder ────────────────────────────────────────────────────────
    "core2.recorder.backend_unavailable": (
        "无法加载音频后端(sounddevice/PortAudio)。Linux 需 `apt install libportaudio2`;其余"
        "平台 wheel 应自带。"
    ),
    "core2.recorder.start_failed": "开始录音失败(可能无麦克风):{error}",
    "core2.recorder.not_recording": "当前未在录音。",
    "core2.recorder.no_audio": "没有录到音频(可能麦克风无输入)。",

    # ── input/attachments ────────────────────────────────────────────────────
    "core2.attachments.unsupported_format": (
        "unsupported / 不支持的图片格式: {media_type!r}。支持的格式: {supported}"
    ),
    "core2.attachments.too_large": (
        "图片超过 5MB 上限 (actual={size:.1f}MB)。请压缩或裁剪后重试。"
    ),
}

